### ISSUE TITLE
Question: Will The CNDP Interface Be Visible In The Kernel Space

### ISSUE THREAD

**Issue by infinitydon** [intel/afxdp-plugins-for-kubernetes#3]
Hi,

I have some questions regarding the behavior of cndp based interfaces.

Once the cndp based interface is injected to the POD:

- Will the interface be visible in the kernel space like using normal Linux commands ifconfig/iproute2?
- Is there a strict need for an additional software/library to be installed before the interface can be used?

**Comment by garyloug** [comment]
Hi @infinitydon 

My apologies for the slow reply, I missed this issue.

> Will the interface be visible in the kernel space like using normal Linux commands ifconfig/iproute2?

No, it will not be visible from the host. Container networking usually means moving interfaces from host to container network namespace. The interface will no longer be visible if you run ifconfig, ip, etc.
You can however exec into the pod and you'll find your interface visible there using these commands.

> Is there a strict need for an additional software/library to be installed before the interface can be used?

There shouldn't be. It depends how you deploy the plugins. They are intended to be deployed within a daemonset and in this scenario everything is packaged up for you in the [docker image](https://github.com/intel/afxdp-plugins-for-kubernetes/blob/main/images/amd64.dockerfile). Once you run this on top of kernel 4.20+ then it should just work. 

When we're testing/developing these plugins we sometimes manually run the plugin binaries directly on the host. In this case you'll need some dependencies installed on the host such as libbpf.


FYI:
1. we're currently working on swapping out the deprecated libbpf for the newer libxdp library
2. the docker image I mentioned, you need to build that yourself (`make image`). We're currently working on getting the image published somewhere like dockerhub, so there will be no need for this manual step soon. 

KR,
Gary
